-- Keel's baseline schema: every table the framework itself needs, from nothing.
--
-- Applied by scripts/init-db.php on a fresh database. After that, schema changes go in
-- scripts/migrations/ and are applied by scripts/migrate.php — do NOT edit this file to change a
-- live database, because nothing re-runs it.
--
-- Conventions used throughout, and worth keeping in your own tables:
--
--   * Every table has an integer `id` (internal, the foreign-key target) AND a `uid` UUID
--     (public-facing). URLs and API responses use `uid`. A sequential integer in a URL tells
--     anyone who looks how many rows you have and invites them to walk the rest.
--   * `deleted TINYINT(1)` is a soft delete. Framework\Model\Model filters it on every read.
--   * Timestamps are DATETIME in UTC. Framework\Database pins the MySQL session to '+00:00' on every
--     connection, so PHP-written and MySQL-written times agree — see the long comment there.
--   * utf8mb4 everywhere. Not utf8, which is three bytes and cannot store an emoji.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ── users ─────────────────────────────────────────────────────────────────────────────────────

CREATE TABLE `users` (
    `id`                           INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid`                          CHAR(36) NOT NULL DEFAULT '',
    `first_name`                   VARCHAR(255) NOT NULL DEFAULT '',
    `last_name`                    VARCHAR(255) NOT NULL DEFAULT '',
    `email`                        VARCHAR(255) NOT NULL,
    `password`                     VARCHAR(255) NOT NULL DEFAULT '',
    -- Platform staff. Read through Framework\Auth::isAdmin(), which asks about the REAL logged-in user
    -- so an impersonated session can never gain admin.
    `is_admin`                     TINYINT(1) NOT NULL DEFAULT 0,

    -- Sign-in throttling. The backoff ladder lives in AuthController::LOGIN_DELAYS_SECONDS.
    `failed_login_attempts`        INT UNSIGNED NOT NULL DEFAULT 0,
    `locked_until`                 DATETIME NULL,

    -- Optional PIN lock, separate from the password: a short code for re-entry on a trusted device.
    `pin_hash`                     VARCHAR(255) NULL,
    `pin_enabled`                  TINYINT(1) NOT NULL DEFAULT 0,
    `failed_pin_attempts`          INT UNSIGNED NOT NULL DEFAULT 0,
    `pin_locked_until`             DATETIME NULL,

    -- Two-factor. `two_factor_secret` is a TOTP seed and is encrypted at rest by
    -- Framework\Security\Crypto — it is TEXT because ciphertext is longer than the seed.
    `two_factor_enabled`           TINYINT(1) NOT NULL DEFAULT 0,
    `two_factor_method`            VARCHAR(10) NOT NULL DEFAULT 'none',
    `two_factor_secret`            TEXT NULL,
    `phone_number`                 VARCHAR(20) NULL,
    `two_factor_prompt_snoozed_at` DATETIME NULL,

    `deleted`                      TINYINT(1) NOT NULL DEFAULT 0,

    PRIMARY KEY (`id`),
    UNIQUE KEY `users_uid` (`uid`),
    -- Enforced here as well as in application code. Two rows with the same address is not a
    -- cosmetic problem: it is an account-takeover vector the moment anything resolves a user BY
    -- address, which password reset and invitation acceptance both do.
    UNIQUE KEY `users_email` (`email`),
    KEY `users_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── organizations ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE `organizations` (
    `id`                      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid`                     CHAR(36) NOT NULL DEFAULT '',
    -- May be blank: the company field is optional at signup, and displayName() shows a default.
    -- Stored raw so edit forms start empty and support can tell the unnamed ones apart by owner.
    `name`                    VARCHAR(255) NOT NULL DEFAULT '',
    `email`                   VARCHAR(255) NOT NULL,

    `stripe_customer_id`      VARCHAR(100) NULL,
    `stripe_subscription_id`  VARCHAR(100) NULL,
    `stripe_card_brand`       VARCHAR(20) NULL,
    `stripe_card_last4`       CHAR(4) NULL,
    -- Stripe's status, mirrored. Entitlement is decided from THIS, not from an API call, so the
    -- application keeps working when Stripe is slow or unreachable.
    `subscription_status`     VARCHAR(20) NULL,
    `subscription_quantity`   INT UNSIGNED NOT NULL DEFAULT 1,
    `subscription_renewal_at` INT NULL,
    -- When the current dunning episode started. Drives the grace window; see
    -- OrganizationModel::graceEndsAt().
    `past_due_since`          INT NULL,
    `lapsed_at`               INT NULL,

    `postal_address`          VARCHAR(255) NULL,
    `deleted`                 TINYINT(1) NOT NULL DEFAULT 0,

    PRIMARY KEY (`id`),
    UNIQUE KEY `organizations_uid` (`uid`),
    KEY `organizations_customer` (`stripe_customer_id`),
    KEY `organizations_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── memberships ───────────────────────────────────────────────────────────────────────────────

CREATE TABLE `memberships` (
    `id`      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid`     CHAR(36) NOT NULL DEFAULT '',
    `user_id` INT UNSIGNED NOT NULL,
    `org_id`  INT UNSIGNED NOT NULL,
    `role`    ENUM('owner','admin','user') NOT NULL DEFAULT 'user',
    `deleted` TINYINT(1) NOT NULL DEFAULT 0,

    PRIMARY KEY (`id`),
    UNIQUE KEY `memberships_uid` (`uid`),
    -- `deleted` is PART of the unique key, and that is load-bearing. Removing a member is a SOFT
    -- delete, so a plain (user_id, org_id) unique index makes re-inviting someone you removed fail
    -- on a row nobody can see. Including `deleted` lets the removed row coexist with the new one.
    UNIQUE KEY `memberships_user_org` (`user_id`, `org_id`, `deleted`),
    KEY `memberships_org` (`org_id`),
    CONSTRAINT `fk_memberships_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_memberships_org` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── invitations ───────────────────────────────────────────────────────────────────────────────

CREATE TABLE `invitations` (
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `org_id`      INT UNSIGNED NOT NULL,
    `email`       VARCHAR(255) NOT NULL,
    `role`        ENUM('owner','admin','user') NOT NULL DEFAULT 'user',
    `token`       VARCHAR(64) NOT NULL,
    `accepted_at` DATETIME NULL,
    `expires_at`  DATETIME NOT NULL,
    `deleted`     TINYINT(1) NOT NULL DEFAULT 0,

    -- No `uid`: an invitation is addressed by its token and nothing else.
    PRIMARY KEY (`id`),
    UNIQUE KEY `invitations_token` (`token`),
    KEY `invitations_org` (`org_id`),
    CONSTRAINT `fk_invitations_org` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── password_resets ───────────────────────────────────────────────────────────────────────────

CREATE TABLE `password_resets` (
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid`        CHAR(36) NOT NULL DEFAULT '',
    `user_id`    INT UNSIGNED NOT NULL,
    -- SHA-256 hex of the token, never the token itself. A reset row is a bearer credential: with
    -- the plaintext in the table, read access to the database is account takeover for everyone who
    -- has an unexpired reset outstanding. 64 chars is exactly a hex digest.
    `token`      VARCHAR(64) NOT NULL,
    `expires_at` DATETIME NOT NULL,
    `used_at`    DATETIME NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `password_resets_uid` (`uid`),
    UNIQUE KEY `password_resets_token` (`token`),
    KEY `password_resets_user` (`user_id`),
    CONSTRAINT `fk_password_resets_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── remember_tokens ───────────────────────────────────────────────────────────────────────────

CREATE TABLE `remember_tokens` (
    `id`              INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`         INT UNSIGNED NOT NULL,
    -- Split selector/validator. The cookie carries both; the lookup is by `selector` (indexed,
    -- constant-time-irrelevant) and the secret half is compared as a hash. A single-token scheme
    -- either needs an indexed secret or a table scan, and the first leaks it to anyone with read
    -- access.
    `selector`        CHAR(18) NOT NULL,
    `validator_hash`  CHAR(64) NOT NULL,
    `expires_at`      DATETIME NOT NULL,
    -- Set when the user asked to skip two-factor on this device. Separate from `expires_at`
    -- because trusting a device for 2FA is a shorter promise than staying signed in on it.
    `trust_2fa_until` DATETIME NULL,
    `device_label`    VARCHAR(255) NULL,
    `ip_address`      VARCHAR(45) NULL,
    `last_used_at`    DATETIME NULL,
    `created_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `remember_tokens_selector` (`selector`),
    KEY `remember_tokens_user` (`user_id`),
    CONSTRAINT `fk_remember_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── pending_signups ───────────────────────────────────────────────────────────────────────────
--
-- Sign-up is two steps, and this is the gap between them. No `users` row exists until the address
-- is verified, so an unverified sign-up cannot squat an email address or be counted as an account.

CREATE TABLE `pending_signups` (
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid`        CHAR(36) NOT NULL DEFAULT '',
    `first_name` VARCHAR(100) NOT NULL,
    `last_name`  VARCHAR(100) NOT NULL DEFAULT '',
    `email`      VARCHAR(255) NOT NULL,
    `org_name`   VARCHAR(255) NOT NULL DEFAULT '',
    `token`      VARCHAR(64) NOT NULL,
    `expires_at` DATETIME NOT NULL,
    `used_at`    DATETIME NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `pending_signups_uid` (`uid`),
    UNIQUE KEY `pending_signups_token` (`token`),
    KEY `pending_signups_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── login_challenges ──────────────────────────────────────────────────────────────────────────
--
-- One in-flight two-factor challenge. Server-side rather than in the session, so the attempt count
-- survives a session the user can clear.

CREATE TABLE `login_challenges` (
    `id`                 INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid`                CHAR(36) NOT NULL DEFAULT '',
    `user_id`            INT UNSIGNED NOT NULL,
    `method`             VARCHAR(10) NOT NULL,
    `code_hash`          VARCHAR(255) NULL,
    `phone_number`       VARCHAR(20) NULL,
    `attempts`           INT UNSIGNED NOT NULL DEFAULT 0,
    -- Whether they ticked "remember me" on the password screen. Carried through the challenge so
    -- the choice survives the second step.
    `remember_requested` TINYINT(1) NOT NULL DEFAULT 0,
    `expires_at`         DATETIME NOT NULL,
    `created_at`         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `login_challenges_uid` (`uid`),
    KEY `login_challenges_user` (`user_id`),
    CONSTRAINT `fk_login_challenges_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── backup_codes ──────────────────────────────────────────────────────────────────────────────

CREATE TABLE `backup_codes` (
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`    INT UNSIGNED NOT NULL,
    `code_hash`  VARCHAR(255) NOT NULL,
    -- Marked rather than deleted, so "I used my last backup code in March" is answerable.
    `used_at`    DATETIME NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    KEY `backup_codes_user` (`user_id`),
    CONSTRAINT `fk_backup_codes_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── admin_events ──────────────────────────────────────────────────────────────────────────────
--
-- The activity log. Append-only: nothing in the application updates or deletes a row here except
-- the retention prune. Written through Framework\Accounts\Service\AdminLog, never directly.
--
-- The labels are DENORMALIZED on purpose. A log that JOINs to render is a log that changes when
-- the rows it points at change — rename an organization and last year's entries silently start
-- describing a name nobody used at the time. These columns say what was true when it happened.

CREATE TABLE `admin_events` (
    `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `event`           VARCHAR(64) CHARACTER SET ascii NOT NULL,
    `category`        VARCHAR(24) CHARACTER SET ascii NOT NULL,
    `summary`         VARCHAR(255) NOT NULL,
    `actor_user_id`   INT UNSIGNED NULL,
    `actor_label`     VARCHAR(160) NOT NULL DEFAULT '',
    `org_id`          INT UNSIGNED NULL,
    `org_label`       VARCHAR(160) NOT NULL DEFAULT '',
    `subject_user_id` INT UNSIGNED NULL,
    `subject_label`   VARCHAR(160) NOT NULL DEFAULT '',
    -- Was the actor impersonating someone? A staff member acting as a customer looks identical to
    -- the customer in every other record we keep, so this column is the only place it is visible.
    `impersonated`    TINYINT(1) NOT NULL DEFAULT 0,
    `ip`              VARCHAR(45) CHARACTER SET ascii NOT NULL DEFAULT '',
    `meta`            JSON NULL,

    -- No foreign keys. This outlives the rows it describes: deleting a user must not delete the
    -- record of what they did, which is exactly when you most want to read it.
    PRIMARY KEY (`id`),
    KEY `ae_time` (`created_at`),
    KEY `ae_org_time` (`org_id`, `created_at`),
    KEY `ae_subject_time` (`subject_user_id`, `created_at`),
    KEY `ae_event_time` (`event`, `created_at`),
    KEY `ae_actor_time` (`actor_user_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── rate_limit_hits ───────────────────────────────────────────────────────────────────────────
--
-- One row per attempt, in a named bucket. Counted over a sliding window by
-- Framework\Accounts\Service\PublicFormGuard and pruned by age. Email-scoped buckets store a HASH of
-- the address, so this table can never become a list of contactable addresses.

CREATE TABLE `rate_limit_hits` (
    `id`         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bucket`     VARCHAR(191) CHARACTER SET ascii NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    KEY `rlh_bucket_time` (`bucket`, `created_at`),
    KEY `rlh_time` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── migrations ────────────────────────────────────────────────────────────────────────────────
--
-- Which files in scripts/migrations/ have run. init-db.php stamps nothing here: a fresh database
-- built from this file is already current, and every migration that exists was written against a
-- schema this file already includes.

CREATE TABLE `migrations` (
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `filename`   VARCHAR(255) NOT NULL,
    `applied_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `migrations_filename` (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
